title: 3D Printing Quick Reference
description: >- # this means to ignore newlines until "baseurl:"
  Spark Makerspace Electronics & Technology Lab
baseurl: "/" 
url: "http://3d-printing-guide.sparkmakerspace.org"
sass:
  quiet_deps: true
theme: minima
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - README.md
